apiVersion: v1
kind: ConfigMap
data:
  KAFKA_CONSUMER_URL: kafkacluster.default.svc.cluster.local:9092
  KAFKA_TOPIC: location
metadata:
  name: locationingester-cfg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: locationingester
  name: locationingester
spec:
  replicas: 1
  selector:
    matchLabels:
      service: locationingester
  template:
    metadata:
      labels:
        service: locationingester
    spec:
      containers:
        - image: stephanstu/locationingester:latest
          name: locationingester
          imagePullPolicy: Always
          env:
            - name: KAFKA_CONSUMER_URL
              valueFrom:
                configMapKeyRef:
                  name: locationingester-cfg
                  key: KAFKA_CONSUMER_URL
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: locationingester-cfg
                  key: KAFKA_TOPIC
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name : DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_PORT
      restartPolicy: Always
